sudo: false

language: php

php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- hhvm

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

before_install:
  - npm install -g npm@latest

install:
  - phpenv local 5.6
  - composer self-update
  - composer install
  - phpenv local --unset

script:
  - npm install -g grunt-cli
  - npm install --no-optional
  - grunt
